# docker-compose -f docker-compose.test.yml --env-file docker-test.env up / down

version: '3.8'
networks:
  messenger-net:
    name: messenger-net
    driver: bridge
volumes:
  mongo-data:
  mongo-config:
  mongo-log:
  postgres-data:
  postgres-log:
  pgadmin-data:
  pgadmin-servers:
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    networks:
      - messenger-net
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - mongo-log:/var/log/mongodb
    env_file:
      - mongodb/mongo-${PROFILE}.env
  mongo_express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    container_name: mongo_express
    networks:
      - messenger-net
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:8081"
    depends_on:
      - "mongo"
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    networks:
      - messenger-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
      - ./postgresql/init:/docker-entrypoint-initdb.d
    env_file:
      - postgresql/postgres-${PROFILE}.env
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin4
    restart: always
    networks:
      - messenger-net
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    - pgadmin-servers:/pgadmin4/servers.json
    env_file:
      - postgresql/pgadmin-${PROFILE}.env
  sub_module:
    image: training:${SUB_MODULE_VERSION}
    container_name: sub_module
    build:
      context: ./sub_module
    environment:
      PROFILE: ${PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/submodule
    networks:
      - messenger-net
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ~/sub_module/logs:/log
      - ~/sub_module/config:/config
    depends_on:
      - 'postgres'
