spring:
  jpa:
    hibernate:
      ddl-auto: none
user:
  oauth:
    clientId: T2dpxQ3vPrtfyF72
    clientSecret: fDw7MpHk5czHNuSRtLhGmAGL42CaxQB9

# Custom
auth:
  totp:
    secret.length: 20
    windowInSec: 30
#   не используется
    maxAttempts: 3