spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
jwt:
  jks.pass: ${JKS_PASS}
  ttl: 604800 # 60 × 60 × 24 × 7
otp:
  secret.length: 128
  code.length: 6
  expiration.period: 5
