#!/bin/bash

DATABASE_NAME="submodule"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	    CREATE USER $DATABASE_NAME;
	    CREATE DATABASE $DATABASE_NAME;
	    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_NAME;
EOSQL
